=== tiwm23tig01/tiwm23tig01/ProjTecInt/autores.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="autores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autor" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="numero" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tiwm23tig01/tiwm23tig01/autores.xml
<autores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="autores.xsd">

  <autor>
    <nome>André Gonçalves</nome>
    <email>a041002@ipmaia.pt</email>
    <numero>41002</numero>
  </autor>

  <autor>
    <nome>Raquel Allen</nome>
    <email>a041011@ipmaia.pt</email>
    <numero>41011</numero>
  </autor>

  <autor>
    <nome>Vitor Matos</nome>
    <email>a040736@ipmaia.pt</email>
    <numero>40736</numero>
  </autor>

</autores>
